// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiBFDz76amVohrX1JOGOapWYkilXSib_M',
    appId: '1:303042554930:web:3e797555986d017ac5602b',
    messagingSenderId: '303042554930',
    projectId: 'project2-1357e',
    authDomain: 'project2-1357e.firebaseapp.com',
    storageBucket: 'project2-1357e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNBj0Tqd8AA72ACy02YZ_90npuLXQLmtk',
    appId: '1:303042554930:android:2b8965f39981286cc5602b',
    messagingSenderId: '303042554930',
    projectId: 'project2-1357e',
    storageBucket: 'project2-1357e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcY3yKWfmYpgXuFxxWyksTKkXsXOb7mWI',
    appId: '1:303042554930:ios:70f2b833908cc880c5602b',
    messagingSenderId: '303042554930',
    projectId: 'project2-1357e',
    storageBucket: 'project2-1357e.appspot.com',
    iosBundleId: 'com.example.project3',
  );
}
